config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :firstposts
  resources :secondposts
  resources :thirdposts

end

app/models/firstpost.rb
class Firstpost < ActiveRecord::Base
    mount_uploader :image, FirstImageUploaderUploader
end

app/models/secondpost.rb
class Secondpost < ActiveRecord::Base
    mount_uploader :image, SecondImageUploaderUploader
end

app/models/thirdpost.rb
class Thirdpost < ActiveRecord::Base
    mount_uploader :image, ThirdImageUploaderUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/firstposts_controller.rb
class FirstpostsController < ApplicationController
  before_action :set_firstpost, only: [:show, :edit, :update, :destroy]

  # GET /firstposts
  # GET /firstposts.json
  def index
    @firstposts = Firstpost.all
  end

  # GET /firstposts/1
  # GET /firstposts/1.json
  def show
  end

  # GET /firstposts/new
  def new
    @firstpost = Firstpost.new
  end

  # GET /firstposts/1/edit
  def edit
  end

  # POST /firstposts
  # POST /firstposts.json
  def create
    @firstpost = Firstpost.new(firstpost_params)

    respond_to do |format|
      if @firstpost.save
        format.html { redirect_to @firstpost, notice: 'Firstpost was successfully created.' }
        format.json { render :show, status: :created, location: @firstpost }
      else
        format.html { render :new }
        format.json { render json: @firstpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firstposts/1
  # PATCH/PUT /firstposts/1.json
  def update
    respond_to do |format|
      if @firstpost.update(firstpost_params)
        format.html { redirect_to @firstpost, notice: 'Firstpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @firstpost }
      else
        format.html { render :edit }
        format.json { render json: @firstpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firstposts/1
  # DELETE /firstposts/1.json
  def destroy
    @firstpost.destroy
    respond_to do |format|
      format.html { redirect_to firstposts_url, notice: 'Firstpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firstpost
      @firstpost = Firstpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firstpost_params
      params.require(:firstpost).permit(:title, :content, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/secondposts_controller.rb
class SecondpostsController < ApplicationController
  before_action :set_secondpost, only: [:show, :edit, :update, :destroy]

  # GET /secondposts
  # GET /secondposts.json
  def index
    @secondposts = Secondpost.all
  end

  # GET /secondposts/1
  # GET /secondposts/1.json
  def show
  end

  # GET /secondposts/new
  def new
    @secondpost = Secondpost.new
  end

  # GET /secondposts/1/edit
  def edit
  end

  # POST /secondposts
  # POST /secondposts.json
  def create
    @secondpost = Secondpost.new(secondpost_params)

    respond_to do |format|
      if @secondpost.save
        format.html { redirect_to @secondpost, notice: 'Secondpost was successfully created.' }
        format.json { render :show, status: :created, location: @secondpost }
      else
        format.html { render :new }
        format.json { render json: @secondpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondposts/1
  # PATCH/PUT /secondposts/1.json
  def update
    respond_to do |format|
      if @secondpost.update(secondpost_params)
        format.html { redirect_to @secondpost, notice: 'Secondpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @secondpost }
      else
        format.html { render :edit }
        format.json { render json: @secondpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondposts/1
  # DELETE /secondposts/1.json
  def destroy
    @secondpost.destroy
    respond_to do |format|
      format.html { redirect_to secondposts_url, notice: 'Secondpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondpost
      @secondpost = Secondpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondpost_params
      params.require(:secondpost).permit(:title, :content, :image)
    end
end

app/controllers/thirdposts_controller.rb
class ThirdpostsController < ApplicationController
  before_action :set_thirdpost, only: [:show, :edit, :update, :destroy]

  # GET /thirdposts
  # GET /thirdposts.json
  def index
    @thirdposts = Thirdpost.all
  end

  # GET /thirdposts/1
  # GET /thirdposts/1.json
  def show
  end

  # GET /thirdposts/new
  def new
    @thirdpost = Thirdpost.new
  end

  # GET /thirdposts/1/edit
  def edit
  end

  # POST /thirdposts
  # POST /thirdposts.json
  def create
    @thirdpost = Thirdpost.new(thirdpost_params)

    respond_to do |format|
      if @thirdpost.save
        format.html { redirect_to @thirdpost, notice: 'Thirdpost was successfully created.' }
        format.json { render :show, status: :created, location: @thirdpost }
      else
        format.html { render :new }
        format.json { render json: @thirdpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thirdposts/1
  # PATCH/PUT /thirdposts/1.json
  def update
    respond_to do |format|
      if @thirdpost.update(thirdpost_params)
        format.html { redirect_to @thirdpost, notice: 'Thirdpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @thirdpost }
      else
        format.html { render :edit }
        format.json { render json: @thirdpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thirdposts/1
  # DELETE /thirdposts/1.json
  def destroy
    @thirdpost.destroy
    respond_to do |format|
      format.html { redirect_to thirdposts_url, notice: 'Thirdpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thirdpost
      @thirdpost = Thirdpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thirdpost_params
      params.require(:thirdpost).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firstposts_helper.rb
module FirstpostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secondposts_helper.rb
module SecondpostsHelper
end

app/helpers/thirdposts_helper.rb
module ThirdpostsHelper
end

app/views/firstposts/_form.html.erb
<%= form_for(@firstpost) do |f| %>
  <% if @firstpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firstpost.errors.count, "error") %> prohibited this firstpost from being saved:</h2>

      <ul>
      <% @firstpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firstposts/edit.html.erb
<h1>Editing Firstpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @firstpost %> |
<%= link_to 'Back', firstposts_path %>

app/views/firstposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Firstposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firstposts.each do |firstpost| %>
      <tr>
        <td><%= firstpost.title %></td>
        <td><%= firstpost.content %></td>
        <td><%= link_to 'Show', firstpost %></td>
        <td><%= link_to 'Edit', edit_firstpost_path(firstpost) %></td>
        <td><%= link_to 'Destroy', firstpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firstpost', new_firstpost_path %>

app/views/firstposts/new.html.erb
<h1>New Firstpost</h1>

<%= render 'form' %>

<%= link_to 'Back', firstposts_path %>

app/views/firstposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @firstpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @firstpost.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@firstpost.image) %>
</p>

<%= link_to 'Edit', edit_firstpost_path(@firstpost) %> |
<%= link_to 'Back', firstposts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">하진쓰</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/firstposts">게시판1 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/secondposts">게시판2 <span class="sr-only">(current)</span></a>
      </li>
            <li class="nav-item active">
        <a class="nav-link" href="/thirdposts">게시판3 <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/secondposts/_form.html.erb
<%= form_for(@secondpost) do |f| %>
  <% if @secondpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secondpost.errors.count, "error") %> prohibited this secondpost from being saved:</h2>

      <ul>
      <% @secondpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/secondposts/edit.html.erb
<h1>Editing Secondpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @secondpost %> |
<%= link_to 'Back', secondposts_path %>

app/views/secondposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Secondposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secondposts.each do |secondpost| %>
      <tr>
        <td><%= secondpost.title %></td>
        <td><%= secondpost.content %></td>
        <td><%= link_to 'Show', secondpost %></td>
        <td><%= link_to 'Edit', edit_secondpost_path(secondpost) %></td>
        <td><%= link_to 'Destroy', secondpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secondpost', new_secondpost_path %>

app/views/secondposts/new.html.erb
<h1>New Secondpost</h1>

<%= render 'form' %>

<%= link_to 'Back', secondposts_path %>

app/views/secondposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @secondpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @secondpost.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@secondpost.image) %>
</p>

<%= link_to 'Edit', edit_secondpost_path(@secondpost) %> |
<%= link_to 'Back', secondposts_path %>

app/views/thirdposts/_form.html.erb
<%= form_for(@thirdpost) do |f| %>
  <% if @thirdpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thirdpost.errors.count, "error") %> prohibited this thirdpost from being saved:</h2>

      <ul>
      <% @thirdpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thirdposts/edit.html.erb
<h1>Editing Thirdpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @thirdpost %> |
<%= link_to 'Back', thirdposts_path %>

app/views/thirdposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thirdposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thirdposts.each do |thirdpost| %>
      <tr>
        <td><%= thirdpost.title %></td>
        <td><%= thirdpost.content %></td>
        <td><%= link_to 'Show', thirdpost %></td>
        <td><%= link_to 'Edit', edit_thirdpost_path(thirdpost) %></td>
        <td><%= link_to 'Destroy', thirdpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thirdpost', new_thirdpost_path %>

app/views/thirdposts/new.html.erb
<h1>New Thirdpost</h1>

<%= render 'form' %>

<%= link_to 'Back', thirdposts_path %>

app/views/thirdposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @thirdpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @thirdpost.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@thirdpost.image) %>
</p>

<%= link_to 'Edit', edit_thirdpost_path(@thirdpost) %> |
<%= link_to 'Back', thirdposts_path %>